name: Scheduled Tests - DEV

on:
  schedule:
    # Run every day at 1:00 AM Central Time (6:00 AM UTC) - 7 days a week
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual trigger

env:
  ENVIRONMENT: dev

jobs:
  test:
    name: Run Playwright Tests (DEV)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'


      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium


      - name: Run Playwright tests
        run: npm test
        env: 
         BASE_URL: ${{ secrets.DEV_BASE_URL }}
          USERNAME: ${{ secrets.DEV_USERNAME }}
          PASSWORD: ${{ secrets.DEV_PASSWORD }}
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-dev
          path: playwright-report/
          retention-days: 30

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-dev
          path: test-results/
          retention-days: 30
